
[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btclog"

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/go-flags"

[[constraint]]
  branch = "rc1.0"
  name = "github.com/hybridnetwork/hxd"

[[constraint]]
  branch = "rc1.0"
  name = "github.com/hybridnetwork/hxwallet"

[[constraint]]
  branch = "master"
  name = "github.com/hybridnetwork/hxrpcclient"

[[constraint]]
  branch = "master"
  name = "github.com/hybridnetwork/hxutil"

[[constraint]]
  branch = "master"
  name = "github.com/dgrijalva/jwt-go"

[[constraint]]
  branch = "master"
  name = "github.com/go-gorp/gorp"

[[constraint]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/context"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/sessions"

[[constraint]]
  branch = "master"
  name = "github.com/haisum/recaptcha"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/logrotate"

[[constraint]]
  branch = "master"
  name = "github.com/zenazn/goji"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v1.7.x"
  name = "google.golang.org/grpc"
